"""build_tables - collision_grid.npz -> hand_collision_table.h.

Turns the calibrated deep-overlap grid into two monotone "minimum
allowed" tables and emits the C header hand_safety.c includes:

  hct_tb_min[f][rot] - lowest safe thumb_bend given finger curl f and rot
  hct_rot_min[f][tb] - lowest safe thumb_rot given finger curl f and tb

Refuses to write the header unless the gates pass:
  G1  every observed-clash anchor pose is clamped by the tables
  G3  empirically-allowed anchor poses need zero adjustment
  G4  the all-open pose needs zero adjustment
It also prints (informational, not fatal) how much of the empirical
f<600 & tb<600 box the geometry does NOT forbid - those cells stay
covered by the empirical floor kept in hand_safety.c, and only an
on-hand boundary replay may retire that floor.

Usage: venv-geo/bin/python build_tables.py <grid.npz> <links.yaml>
       <out.h>
"""

import hashlib
import sys
import time

import numpy as np
import yaml

STEP = 50
N = 41

ALLOWED_ANCHORS = [(600, 0, 1200), (600, 0, 2000), (0, 600, 1200),
                   (0, 600, 2000), (800, 0, 1200), (2000, 0, 1200),
                   (2000, 0, 2000), (0, 2000, 1200), (600, 600, 1200),
                   (2000, 2000, 2000)]

BAD_ANCHORS = [(0, 0, 1200), (0, 0, 2000), (300, 300, 1200),
               (0, 0, 0), (400, 300, 1500)]


def min_free_from_top(forbidden_1d, targets):
    """Smallest target such that everything at or above it is free."""
    k = len(forbidden_1d)
    while k > 0 and not forbidden_1d[k - 1]:
        k -= 1
    return 2000 + STEP if k == len(forbidden_1d) else int(targets[k])


def build(dist, targets, forbid_below):
    """No monotonisation: interference is NOT monotone in f (half-curled
    fingertips sit right in the thumb's sweep band, worse than a full
    curl), so smoothing would propagate mid-range strictness to poses
    that are actually clear. Conservatism between gridpoints comes from
    the 2x2 neighbour-max lookup instead."""
    forbidden = dist < forbid_below
    tb_min = np.zeros((N, N), dtype=int)
    rot_min = np.zeros((N, N), dtype=int)
    for fi in range(N):
        for ri in range(N):
            tb_min[fi, ri] = min_free_from_top(forbidden[fi, :, ri], targets)
        for bi in range(N):
            rot_min[fi, bi] = min_free_from_top(forbidden[fi, bi, :], targets)
    return tb_min, rot_min


def lookup(tab, primary, secondary):
    """Max over the 2x2 cells enclosing the query point (conservative)."""
    i0 = min(primary // STEP, N - 1)
    j0 = min(secondary // STEP, N - 1)
    i1 = min(i0 + 1, N - 1)
    j1 = min(j0 + 1, N - 1)
    return int(max(tab[i0, j0], tab[i0, j1], tab[i1, j0], tab[i1, j1]))


def clamp_pose(tb_min, rot_min, f, tb, rot):
    """Table clamp iterated to the fixed point (values only rise)."""
    for _ in range(8):
        tb2 = max(tb, lookup(tb_min, f, rot))
        rot2 = max(rot, lookup(rot_min, f, tb2))
        if (tb2, rot2) == (tb, rot):
            break
        tb, rot = tb2, rot2
    return tb, rot


def gates(tb_min, rot_min):
    fails = []
    for f, tb, rot in BAD_ANCHORS:                            # G1
        tb2, rot2 = clamp_pose(tb_min, rot_min, f, tb, rot)
        if (tb2, rot2) == (tb, rot):
            fails.append("G1 clash anchor (%d,%d,%d) not clamped"
                         % (f, tb, rot))
    for f, tb, rot in ALLOWED_ANCHORS:                        # G3
        tb2, rot2 = clamp_pose(tb_min, rot_min, f, tb, rot)
        # boundary anchors may pick up one cell of quantisation nudge
        if tb2 - tb > STEP or rot2 - rot > STEP:
            fails.append("G3 allowed (%d,%d,%d) clamped to tb=%d rot=%d"
                         % (f, tb, rot, tb2, rot2))
    if clamp_pose(tb_min, rot_min, 2000, 2000, 2000) != (2000, 2000):
        fails.append("G4 all-open clamped")
    return fails


def emit(tb_min, rot_min, meta, out_path):
    def rows(tab):
        return ",\n".join("    {" + ", ".join("%4d" % v for v in row) + "}"
                          for row in tab)
    body = """\
/* hand_collision_table.h - GENERATED by geometry/build_tables.py.
 * Do not edit by hand; regenerate from the STEP scan instead.
 *
 * Minimum allowed thumb targets vs finger curl, from the
 * anchor-calibrated deep-overlap scan of the vendor STEP model.
 * f = min(effective index, effective middle) on the 0..2000 scale.
 * Lookup MUST take the max over the 2x2 cells enclosing the query
 * point (the tables are deliberately not monotone: half-curled
 * fingers obstruct the thumb more than fully curled ones), and the
 * tb/rot clamps must be iterated to their fixed point.
 *
 * source_step_sha256: %(sha)s
 * generated: %(ts)s
 * calibration: %(cal)s
 * gates: G1 clash-anchor coverage, G3/G4 zero-adjust on allowed
 *        anchors - all passed at generation time.
 */
#ifndef HAND_COLLISION_TABLE_H
#define HAND_COLLISION_TABLE_H

#include <stdint.h>

#define HCT_STEP %(step)d
#define HCT_N    %(n)d

/* lowest safe thumb_bend target, indexed [f/HCT_STEP][rot/HCT_STEP] */
static const int16_t hct_tb_min[HCT_N][HCT_N] = {
%(tb)s
};

/* lowest safe thumb_rot target, indexed [f/HCT_STEP][tb/HCT_STEP] */
static const int16_t hct_rot_min[HCT_N][HCT_N] = {
%(rot)s
};

#endif
""" % {"sha": meta["sha"], "ts": meta["ts"], "cal": meta["cal"],
       "step": STEP, "n": N, "tb": rows(tb_min), "rot": rows(rot_min)}
    with open(out_path, "w") as f:
        f.write(body)


def main(grid_npz, links_yaml, out_path):
    data = np.load(grid_npz)
    cfg = yaml.safe_load(open(links_yaml))
    cal = cfg["calibration"]
    tb_min, rot_min = build(data["dist"], data["targets"],
                            cal["forbid_below_mm"])
    fails = gates(tb_min, rot_min)
    if fails:
        print("GATES FAILED - header NOT written:")
        for f in fails:
            print(" ", f)
        raise SystemExit(1)
    # informational: where is the geometry looser than the empirical box?
    loose = 0
    for fi in range(600 // STEP):
        for ri in range(N):
            if tb_min[fi, ri] < 600:
                loose += 1
    print("info: %d/%d cells of the empirical f<600 box rely on the "
          "floor (geometry sees no deep overlap there)" %
          (loose, (600 // STEP) * N))
    step_sha = "60cc620d"  # overwritten below when the STEP is present
    try:
        h = hashlib.sha256()
        with open("/tmp/rh56f1_geo/仿人五指灵巧手-右.STEP", "rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                h.update(chunk)
        step_sha = h.hexdigest()[:16]
    except OSError:
        pass
    emit(tb_min, rot_min,
         {"sha": step_sha,
          "ts": time.strftime("%Y-%m-%d"),
          "cal": ("mcp_share=%(finger_mcp_share)s "
                  "thumb_share=%(thumb_base_share)s "
                  "sweep_scale=%(thumb_sweep_scale)s shrink=%(shrink)s "
                  "forbid_below_mm=%(forbid_below_mm)s") % cal},
         out_path)
    print("gates OK, wrote", out_path)
    print("tb_min[f=0] :", tb_min[0])
    print("tb_min[f=600//125=4]:", tb_min[4])
    print("tb_min[f=2000]:", tb_min[16])
    print("rot_min[f=0]:", rot_min[0])


if __name__ == "__main__":
    main(*sys.argv[1:4])
